"""
Wordlists for Deterministic Sensitive Data Proofchecker.
Contains 300+ sensitive tactical keywords categorized across:
1. Credentials, Private Keys, Authentication Tokens & Secrets
2. Operational Markings, Classifications & Defensive Directives
3. Threat Intel Infrastructure, C2 Indicators & Sensitive Anchors
4. Threat Intel Artifacts, Registry Hives, Hashes & Exploitation Tools
"""

from typing import List

SENSITIVE_KEYWORDS: List[str] = [
    # ── 1. Auth, Credentials, Private Keys & Secrets (~135 keywords) ──
    "AWS_SECRET_ACCESS_KEY",
    "AWS_ACCESS_KEY_ID",
    "AWS_SESSION_TOKEN",
    "AWS_SECURITY_TOKEN",
    "ROOT_PASSWORD",
    "SSH_PRIVATE_KEY",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "id_rsa_priv",
    "id_rsa.pub",
    "AUTHORIZATION",
    "BEARER",
    "BEGIN RSA PRIVATE KEY",
    "BEGIN PRIVATE KEY",
    "BEGIN OPENSSH PRIVATE KEY",
    "BEGIN DSA PRIVATE KEY",
    "BEGIN EC PRIVATE KEY",
    "BEGIN PGP PRIVATE KEY BLOCK",
    "BEGIN ENCRYPTED PRIVATE KEY",
    "BEGIN CERTIFICATE",
    "END RSA PRIVATE KEY",
    "END PRIVATE KEY",
    "END OPENSSH PRIVATE KEY",
    "END DSA PRIVATE KEY",
    "END EC PRIVATE KEY",
    "END PGP PRIVATE KEY BLOCK",
    "passwd",
    "shadow",
    "api_token",
    "api_secret",
    "api_key",
    "access_token",
    "refresh_token",
    "client_secret",
    "secret_key",
    "master_key",
    "private_key",
    "privkey",
    "encryption_key",
    "jwt_secret",
    "jwt_key",
    "database_password",
    "db_password",
    "db_pass",
    "admin_password",
    "admin_pass",
    "root_pass",
    "root_pwd",
    "ldap_password",
    "kerberos_ticket",
    "ntlm_hash",
    "sam_database",
    "lsass_dump",
    "mimikatz",
    "vault_token",
    "kubeconfig",
    "docker_auth",
    "htpasswd",
    "wp-config.php",
    "conn_string",
    "connection_string",
    "bearer_token",
    "oauth_token",
    "session_secret",
    "auth_token",
    "x-api-key",
    "x-auth-token",
    "x-amz-security-token",
    "slack_token",
    "discord_webhook",
    "sendgrid_api_key",
    "stripe_secret_key",
    "twilio_auth_token",
    "mailgun_api_key",
    "pagerduty_token",
    "datadog_api_key",
    "splunk_token",
    "newrelic_license_key",
    "firebase_secret",
    "algolia_api_key",
    "heroku_api_key",
    "circleci_token",
    "travis_token",
    "sonarqube_token",
    "vault_addr",
    "consul_token",
    "etcd_root_password",
    "rabbitmq_password",
    "redis_password",
    "postgres_password",
    "mysql_password",
    "sql_password",
    "oracle_sys_password",
    "mongodb_secret",
    "s3_access_key",
    "azure_client_secret",
    "gcp_service_account",
    "privkey.pem",
    "server.key",
    "ca.key",
    "client.key",
    "keystore.jks",
    "cert.pfx",
    "client.p12",
    "secring.gpg",
    "gpg_secret_key",
    "seed_phrase",
    "bip39_mnemonic",
    "wallet_private_key",
    "totp_secret",
    "mfa_secret",
    "otp_secret",
    "backup_codes",
    "recovery_key",
    "passphrase",
    "hardware_token_seed",
    "yubikey_secret",
    "okta_api_token",
    "onelogin_token",
    "ping_identity_secret",
    "azuread_app_secret",
    "entraid_client_secret",
    "jira_pat_token",
    "confluence_pat",
    "github_pat",
    "gitlab_pat",
    "bitbucket_app_password",
    "kms_key_secret",
    "keyvault_secret",
    "ansible_vault_password",
    "terraform_secret",
    "aws_signature",
    "gcp_oauth_token",
    "azure_storage_key",

    # ── 2. Operational Markings & Classifications (~75 keywords) ──
    "TOP SECRET",
    "NOFORN",
    "RESTRICTED OPERATION",
    "LAW ENFORCEMENT SENSITIVE",
    "SECRET//SI",
    "INTERNAL EYES ONLY",
    "SECRET//NOFORN",
    "TOP SECRET//SCI",
    "TOP SECRET//SI",
    "TOP SECRET//TK",
    "TOP SECRET//NOFORN",
    "SECRET//REL TO",
    "CONFIDENTIAL//REL TO",
    "CONFIDENTIAL//NOFORN",
    "ORCON",
    "PROPIN",
    "FOUO",
    "FOR OFFICIAL USE ONLY",
    "RESTRICTED DATA",
    "FORMERLY RESTRICTED DATA",
    "COMSEC",
    "SIGINT",
    "HUMINT",
    "GEOINT",
    "MASINT",
    "SPECIAL ACCESS REQUIRED",
    "SAP/SAR",
    "OPERATION SHADOWGATE INTERNAL",
    "INTERNAL ONLY - NOT FOR PUBLIC",
    "STRICTLY CONFIDENTIAL",
    "CUI//SP-SENS",
    "CUI//PRIV",
    "DEA SENSITIVE",
    "FIN INTEL SECRET",
    "TALENT KEYHOLE",
    "GAMMA COMPARTMENT",
    "HCS CLEARANCE",
    "SI COMPARTMENT",
    "TK CLEARANCE",
    "NO DISSEM",
    "CLASSIFIED COMPARTMENT",
    "SEALED INDICTMENT",
    "WIRETAP RECORD",
    "WARRANT IDENTIFIER",
    "RAW SURVEILLANCE LOG",
    "INTERCEPT TRANSCRIPT",
    "UNDERCOVER ALIAS",
    "WITNESS PROTECTION ID",
    "INFORMANT CODE",
    "WHISTLEBLOWER ID",
    "SUBPOENA NOTICE INTERNAL",
    "TAKEDOWN NOTICE INTERNAL",
    "LIMITED DISTRIBUTION",
    "SENSITIVE BUT UNCLASSIFIED",
    "LES/NF",
    "SECRET//ORCON",
    "TOP SECRET//SPECIAL HANDLING",
    "RESTRICTED DISSEMINATION",
    "NOT FOR DISTRIBUTION",
    "CONFIDENTIAL ATTORNEY CLIENT",
    "PRIVILEGED AND CONFIDENTIAL",
    "CRITICAL INFRASTRUCTURE DEFENSE",
    "RESTRICTED TELEMETRY STREAM",
    "NATIONAL SECURITY DIRECTIVE",
    "CONTROLLED UNCLASSIFIED INFORMATION",
    "INTERNAL EYES ONLY - RESTRICTED",
    "NON-DISCLOSURE RESTRICTED",
    "ITAR RESTRICTED",
    "EXPORT CONTROLLED DATA",
    "GOVERNMENT PURPOSE RIGHTS",
    "PROPRIETARY COMMERCIAL SECRET",

    # ── 3. Threat Intel Sensitive Identifiers & Infrastructure (~75 keywords) ──
    "DEFANGED_IOC",
    "IMMEDIATE_TAKEDOWN",
    "HONEYPOT_BASTION",
    "INTERNAL_C2_SINKHOLE",
    "SINKHOLE_AGENT",
    "BASTION_GATEWAY",
    "CANARY_TOKEN",
    "COBALT_STRIKE_BEACON",
    "BURP_COLLABORATOR",
    "INTERACTSH",
    "SANGFOR_INTERNAL",
    "TITAN_SENSOR",
    "INTERNAL_TELEMETRY_PIPELINE",
    "DARKNET_DROP",
    "RED_TEAM_STAGING",
    "AIRGAP_BRIDGE",
    "EXFIL_DROPZONE",
    "IMPLANT_UUID",
    "BACKDOOR_KEY",
    "MALWARE_SAMPLE_UNSTRIPPED",
    "ZERO_DAY_EXPLOIT",
    "CORE_DB_PROD",
    "BANK_HSM",
    "DC_INTERNAL_AUTH",
    "C2_INFRASTRUCTURE_SECRET",
    "COVERT_CHANNEL_KEY",
    "COVERT_ASSET_ID",
    "SAFEHOUSE_LOCATION",
    "EXFIL_SERVER_IP",
    "STAGING_BASTION_HOST",
    "INTERNAL_JUMP_SERVER",
    "ISOLATED_ENCLAVE_HOST",
    "PRODUCTION_HSM_ENDPOINT",
    "PKI_ROOT_CA_BUNDLE",
    "INTERNAL_PKI_PRIVKEY",
    "CODE_SIGNING_PRIVKEY",
    "INTERNAL_DNS_ROOT",
    "INTERNAL_PROXY_BYPASS",
    "SANDBOX_EVASION_TRIGGER",
    "KILLSWITCH_DOMAIN",
    "MUTEX_INDICATOR",
    "COMMAND_AND_CONTROL_NODE",
    "EXPLOIT_PAYLOAD_DROPPER",
    "STAGER_SHELLCODE",
    "REFLECTIVE_DLL_INJECTION",
    "PROCESS_HOLLOWING_TARGET",
    "ROOTKIT_HOOK",
    "BOOTKIT_SECTOR",
    "FIRMWARE_BACKDOOR",
    "VULNERABILITY_RESEARCH_INTERNAL",
    "ZERO_CLICK_CHAIN",
    "TAO_CATALOG_ID",
    "PEGASUS_IMPLANT",
    "PRE_AUTH_RCE",
    "CRITICAL_INFRASTRUCTURE_TARGET",
    "SCADA_CONTROLLER_KEY",
    "PLC_FIRMWARE_KEY",
    "OT_NETWORK_ENCLAVE",
    "SAFETY_SYSTEM_OVERRIDE",
    "CAN_BUS_INJECTOR",
    "OBD_EXPLOIT_PACKET",
    "ECU_FLASH_SECRET",
    "GATEWAY_ROUTER_BYPASS",
    "TELEMETRY_SNIFFER_LOG",
    "SATELLITE_UPLINK_KEY",
    "RADAR_TELEMETRY_FEED",
    "LIDAR_SENSOR_EXPLOIT",

    # ── 4. Threat Intel Artifacts, Hives, Hashes & Post-Exploitation (~75 keywords) ──
    "/etc/passwd",
    "/etc/shadow",
    "/etc/sudoers",
    "/etc/gshadow",
    "/etc/master.passwd",
    "authorized_keys",
    "known_hosts",
    ".bash_history",
    ".zsh_history",
    "SAM_HIVE",
    "SYSTEM_HIVE",
    "NTDS.DIT",
    "SECURITY_HIVE",
    "admin_hash",
    "root_hash",
    "user_hash",
    "password_hash",
    "hashcat_potfile",
    "john_potfile",
    "responder_session",
    "ntlmv2_response",
    "smb_relay_hash",
    "bloodhound_db",
    "sharphound_cache",
    "rubeus_ticket",
    "psexec_svc",
    "wmiexec_output",
    "impacket_session",
    "sqlmap_dump",
    "nmap_secret_output",
    "nessus_credential_dump",
    "metasploit_db",
    "meterpreter_session",
    "empire_stager",
    "havoc_demon",
    "sliver_beacon",
    "mythic_payload",
    "covenant_grunt",
    "brute_ratel_badger",
    "poshc2_implant",
    "shad0w_beacon",
    "koadic_zombie",
    "powershell_empire",
    "golden_ticket",
    "silver_ticket",
    "skeleton_key",
    "asreproast",
    "kerberoast",
    "dcsync",
    "netntlmv2",
    "bcrypt_hash",
    "argon2_hash",
    "procdump_lsass",
    "nanodump_out",
    "handlekatz_dump",
    "seclists_top10k",
    "rockyou_wordlist",
    "dirsearch_report",
    "nuclei_secrets_scan",
    "trufflehog_verified",
    "gitleaks_matched",
    "sublist3r_output",
    "amass_database",
    "recon_ng_workspace",
    "burp_project_file",
    "zaproxy_session",
    "wireshark_pcap_secret",
    "tcpdump_exfil_raw",
    "volatility_memdump",
    "rekall_profile",
]

# Ensure unique preserving order
_seen = set()
KALI_SECLISTS_KEYWORDS: List[str] = [
    kw for kw in SENSITIVE_KEYWORDS if not (kw in _seen or _seen.add(kw))
]
